name: coy
version: 0.1.0.0
github: "zuqq/coy"
author: "zuqq"

extra-source-files:
- README.md

dependencies:
- algebraic-graphs
- attoparsec
- attoparsec-expr
- base >= 4.7 && < 5
- bytestring
- containers
- ilist
- llvm-hs-pretty
- llvm-hs-pure
- microlens
- microlens-mtl
- mtl
- text
- transformers
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  coy-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coy

tests:
  coy-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coy
