resolver: lts-18.1
packages:
- .
extra-deps:
- github: llvm-hs/llvm-hs
  commit: fb9b5006704404cb5768873f828ffa883873ef07
  subdirs:
  - llvm-hs-pure
- github: zuqq/llvm-hs-pretty
  commit: 322e8de20bc60cdfd342840f61dd65ce5fb1b961
