resolver: lts-19.11
packages:
- .
extra-deps:
- github: llvm-hs/llvm-hs
  commit: fb9b5006704404cb5768873f828ffa883873ef07
  subdirs:
  - llvm-hs-pure
- github: zuqq/llvm-hs-pretty
  commit: a5ba79623a5aa28d7cc36d8e8c8dcd31f13ce30b
